-- Alex Zaharia
-- azaharia@calpoly.edu
-- May 2, 2023

INSERT INTO customers VALUES (1,  'LOGAN',  'JULIET');
INSERT INTO customers VALUES (2,  'ARZT',  'TERRELL');
INSERT INTO customers VALUES (3,  'ESPOSITA',  'TRAVIS');
INSERT INTO customers VALUES (4,  'ENGLEY',  'SIXTA');
INSERT INTO customers VALUES (5,  'DUNLOW',  'OSVALDO');
INSERT INTO customers VALUES (6,  'SLINGLAND',  'JOSETTE');
INSERT INTO customers VALUES (7,  'TOUSSAND',  'SHARRON');
INSERT INTO customers VALUES (8,  'HELING',  'RUPERT');
INSERT INTO customers VALUES (9,  'HAFFERKAMP',  'CUC');
INSERT INTO customers VALUES (10,  'DUKELOW',  'CORETTA');
INSERT INTO customers VALUES (11,  'STADICK',  'MIGDALIA');
INSERT INTO customers VALUES (12,  'MCMAHAN',  'MELLIE');
INSERT INTO customers VALUES (13,  'ARNN',  'KIP');
INSERT INTO customers VALUES (14,  'SOPKO',  'RAYFORD');
INSERT INTO customers VALUES (15,  'CALLENDAR',  'DAVID');
INSERT INTO customers VALUES (16,  'CRUZEN',  'ARIANE');
INSERT INTO customers VALUES (17,  'MESDAQ',  'CHARLENE');
INSERT INTO customers VALUES (18,  'DOMKOWSKI',  'ALMETA');
INSERT INTO customers VALUES (19,  'STENZ',  'NATACHA');
INSERT INTO customers VALUES (20,  'ZEME',  'STEPHEN');