-- Alex Zaharia
-- azaharia@calpoly.edu
-- May 2, 2023

INSERT INTO airports100 VALUES ('Aberdeen ', 'APG', 'Phillips AAF ', 'United States ', 'US ');
INSERT INTO airports100 VALUES ('Aberdeen ', 'ABR', 'Municipal ', 'United States ', 'US ');
INSERT INTO airports100 VALUES ('Abilene ', 'DYS', 'Dyess AFB ', 'United States ', 'US ');
INSERT INTO airports100 VALUES ('Abilene ', 'ABI', 'Municipal ', 'United States ', 'US ');
INSERT INTO airports100 VALUES ('Abingdon ', 'VJI', 'Virginia Highlands ', 'United States ', 'US ');
INSERT INTO airports100 VALUES ('Ada ', 'ADT', 'Ada ', 'United States ', 'US ');
INSERT INTO airports100 VALUES ('Adak Island ', 'ADK', 'Adak Island Ns ', 'United States ', 'US ');
INSERT INTO airports100 VALUES ('Adrian ', 'ADG', 'Lenawee County ', 'United States ', 'US ');
INSERT INTO airports100 VALUES ('Afton ', 'AFO', 'Municipal ', 'United States ', 'US ');
INSERT INTO airports100 VALUES ('Aiken ', 'AIK', 'Municipal ', 'United States ', 'US ');
INSERT INTO airports100 VALUES ('Ainsworth ', 'ANW', 'Ainsworth ', 'United States ', 'US ');
INSERT INTO airports100 VALUES ('Akhiok ', 'AKK', 'Akhiok SPB ', 'United States ', 'US ');
INSERT INTO airports100 VALUES ('Akiachak ', 'KKI', 'Spb ', 'United States ', 'US ');
INSERT INTO airports100 VALUES ('Akiak ', 'AKI', 'Akiak ', 'United States ', 'US ');
INSERT INTO airports100 VALUES ('Akron CO ' , 'AKO', 'Colorado Plains Regional Airport ', 'United States ', 'US ');
INSERT INTO airports100 VALUES ('Akron/Canton OH ' , 'CAK', 'Akron/canton Regional ', 'United States ', 'US ');
INSERT INTO airports100 VALUES ('Akron/Canton ', 'AKC', 'Fulton International ', 'United States ', 'US ');
INSERT INTO airports100 VALUES ('Akutan ', 'KQA', 'Akutan ', 'United States ', 'US ');
INSERT INTO airports100 VALUES ('Alakanuk ', 'AUK', 'Alakanuk ', 'United States ', 'US ');
INSERT INTO airports100 VALUES ('Alameda ', 'NGZ', 'NAS ', 'United States ', 'US ');
INSERT INTO airports100 VALUES ('Alamogordo ', 'HMN', 'Holloman AFB ', 'United States ', 'US ');
INSERT INTO airports100 VALUES ('Alamogordo ', 'ALM', 'Municipal ', 'United States ', 'US ');
INSERT INTO airports100 VALUES ('Alamosa ', 'ALS', 'Municipal ', 'United States ', 'US ');
INSERT INTO airports100 VALUES ('Albany ', 'NAB', 'Albany NAS ', 'United States ', 'US ');
INSERT INTO airports100 VALUES ('Albany ', 'ABY', 'Dougherty County ', 'United States ', 'US ');
INSERT INTO airports100 VALUES ('Albany ', 'ALB', 'Albany International ', 'United States ', 'US ');
INSERT INTO airports100 VALUES ('Albany ', 'CVO', 'Albany ', 'United States ', 'US ');
INSERT INTO airports100 VALUES ('Albert Lea ', 'AEL', 'Albert Lea ', 'United States ', 'US ');
INSERT INTO airports100 VALUES ('Albuquerque ', 'ABQ', 'Albuquerque International ', 'United States ', 'US ');
INSERT INTO airports100 VALUES ('Aleknagik ', 'WKK', 'Aleknagik ', 'United States ', 'US ');
INSERT INTO airports100 VALUES ('Aleneva ', 'AED', 'Aleneva ', 'United States ', 'US ');
INSERT INTO airports100 VALUES ( 'Alexander City AL ' , 'ALX', 'Thomas C Russell Fld ', 'United States ', 'US ');
INSERT INTO airports100 VALUES ( 'Alexandria LA ' , 'AEX', 'Alexandria International ', 'United States ', 'US ');
INSERT INTO airports100 VALUES ('Alexandria ', 'ESF', 'Esler Field ', 'United States ', 'US ');
INSERT INTO airports100 VALUES ('Alexandria ', 'AXN', 'Alexandria ', 'United States ', 'US ');
INSERT INTO airports100 VALUES ('Alexandria Bay ', 'AXB', 'Alexandria Bay ', 'United States ', 'US ');
INSERT INTO airports100 VALUES ('Algona ', 'AXG', 'Algona ', 'United States ', 'US ');
INSERT INTO airports100 VALUES ('Alice ', 'ALI', 'International ', 'United States ', 'US ');
INSERT INTO airports100 VALUES ( 'Aliceville AL ' , 'AIV', 'George Downer ', 'United States ', 'US ');
INSERT INTO airports100 VALUES ('Alitak ', 'ALZ', 'Alitak SPB ', 'United States ', 'US ');
INSERT INTO airports100 VALUES ('Allakaket ', 'AET', 'Allakaket ', 'United States ', 'US ');
INSERT INTO airports100 VALUES ('Alliance ', 'AIA', 'Alliance ', 'United States ', 'US ');
INSERT INTO airports100 VALUES ('Alma ', 'AMN', 'Gratiot Community ', 'United States ', 'US ');
INSERT INTO airports100 VALUES ('Alpena ', 'APN', 'Alpena County Regional ', 'United States ', 'US ');
INSERT INTO airports100 VALUES ('Alpine ', 'ALE', 'Alpine ', 'United States ', 'US ');
INSERT INTO airports100 VALUES ('Alton ', 'ALN', 'Alton ', 'United States ', 'US ');
INSERT INTO airports100 VALUES ('Altus ', 'LTS', 'Altus AFB ', 'United States ', 'US ');
INSERT INTO airports100 VALUES ('Altus ', 'AXS', 'Municipal ', 'United States ', 'US ');
INSERT INTO airports100 VALUES ('Alyeska ', 'AQY', 'Alyeska ', 'United States ', 'US ');
INSERT INTO airports100 VALUES ( 'Amarillo  ' , 'AMA', 'Rick Husband Amarillo International ', 'United States ', 'US ');
INSERT INTO airports100 VALUES ('Amarillo ', 'TDW', 'Tradewind ', 'United States ', 'US ');
INSERT INTO airports100 VALUES ('Ambler ', 'ABL', 'Ambler ', 'United States ', 'US ');
INSERT INTO airports100 VALUES ('Amchitka ', 'AHT', 'Amchitka ', 'United States ', 'US ');
INSERT INTO airports100 VALUES ('Amery ', 'AHH', 'Municipal ', 'United States ', 'US ');
INSERT INTO airports100 VALUES ('Ames ', 'AMW', 'Ames ', 'United States ', 'US ');
INSERT INTO airports100 VALUES ('Amityville ', 'AYZ', 'Zahns ', 'United States ', 'US ');
INSERT INTO airports100 VALUES ('Amook ', 'AOS', 'Amook ', 'United States ', 'US ');
INSERT INTO airports100 VALUES ('Anacortes ', 'OTS', 'Anacortes ', 'United States ', 'US ');
INSERT INTO airports100 VALUES ('Anacostia ', 'NDV', 'USN Heliport ', 'United States ', 'US ');
INSERT INTO airports100 VALUES ('Anaheim ', 'ANA', 'Orange County Steel Salvage Heliport ', 'United States ', 'US ');
INSERT INTO airports100 VALUES ('Anaktuvuk ', 'AKP', 'Anaktuvuk ', 'United States ', 'US ');
INSERT INTO airports100 VALUES ('Anchorage ', 'EDF', 'Elmendorf Afb ', 'United States ', 'US ');
INSERT INTO airports100 VALUES ('Anchorage ', 'ANC', 'Ted Stevens Anchorage International Airport ', 'United States ', 'US ');
INSERT INTO airports100 VALUES ('Anchorage ', 'MRI', 'Merrill Field ', 'United States ', 'US ');
INSERT INTO airports100 VALUES ('Anderson ', 'AID', 'Municipal ', 'United States ', 'US ');
INSERT INTO airports100 VALUES ('Anderson ', 'AND', 'Anderson ', 'United States ', 'US ');
INSERT INTO airports100 VALUES ('Andrews ', 'ADR', 'Andrews ', 'United States ', 'US ');
INSERT INTO airports100 VALUES ('Angel Fire ', 'AXX', 'Angel Fire ', 'United States ', 'US ');
INSERT INTO airports100 VALUES ('Angola ', 'ANQ', 'Tri-State Steuben Cty ', 'United States ', 'US ');
INSERT INTO airports100 VALUES ('Angoon ', 'AGN', 'Angoon ', 'United States ', 'US ');
INSERT INTO airports100 VALUES ('Anguilla ', 'RFK', 'Rollang Field ', 'United States ', 'US ');
INSERT INTO airports100 VALUES ('Aniak ', 'ANI', 'Aniak ', 'United States ', 'US ');
INSERT INTO airports100 VALUES ('Anita Bay ', 'AIB', 'Anita Bay ', 'United States ', 'US ');
INSERT INTO airports100 VALUES ( 'Ann Arbor MI ' , 'ARB', 'Municipal ', 'United States ', 'US ');
INSERT INTO airports100 VALUES ('Annapolis ', 'ANP', 'Lee ', 'United States ', 'US ');
INSERT INTO airports100 VALUES ('Annette Island ', 'ANN', 'Annette Island ', 'United States ', 'US ');
INSERT INTO airports100 VALUES ( 'Anniston AL ' , 'ANB', 'Anniston Metropolitan ', 'United States ', 'US ');
INSERT INTO airports100 VALUES ('Anniston ', 'QAW', 'Ft Mcclellan Bus Trml ', 'United States ', 'US ');
INSERT INTO airports100 VALUES ('Anniston ', 'RLI', 'Reilly AHP ', 'United States ', 'US ');
INSERT INTO airports100 VALUES ('Anthony ', 'ANY', 'Anthony ', 'United States ', 'US ');
INSERT INTO airports100 VALUES ('Antlers ', 'ATE', 'Antlers ', 'United States ', 'US ');
INSERT INTO airports100 VALUES ('Anvik ', 'ANV', 'Anvik ', 'United States ', 'US ');
INSERT INTO airports100 VALUES ('Apalachicola ', 'AAF', 'Municipal ', 'United States ', 'US ');
INSERT INTO airports100 VALUES ('Apple Valley ', 'APV', 'Apple Valley ', 'United States ', 'US ');
INSERT INTO airports100 VALUES ('Appleton ', 'ATW', 'Outagamie County ', 'United States ', 'US ');
INSERT INTO airports100 VALUES ('Arapahoe ', 'AHF', 'Municipal ', 'United States ', 'US ');
INSERT INTO airports100 VALUES ('Arcata ', 'ACV', 'Arcata ', 'United States ', 'US ');
INSERT INTO airports100 VALUES ('Arctic Village ', 'ARC', 'Arctic Village ', 'United States ', 'US ');
INSERT INTO airports100 VALUES ('Ardmore ', 'AHD', 'Downtown ', 'United States ', 'US ');
INSERT INTO airports100 VALUES ('Ardmore ', 'ADM', 'Ardmore Municipal Arpt ', 'United States ', 'US ');
INSERT INTO airports100 VALUES ('Arlington Heights ', 'JLH', 'US Army Heliport ', 'United States ', 'US ');
INSERT INTO airports100 VALUES ('Artesia ', 'ATS', 'Artesia ', 'United States ', 'US ');
INSERT INTO airports100 VALUES ( 'Neptune ' , 'ARX', 'Asbury Park ', 'United States ', 'US ');
INSERT INTO airports100 VALUES ('Ashland ', 'ASX', 'Ashland ', 'United States ', 'US ');
INSERT INTO airports100 VALUES ('Ashley ', 'ASY', 'Ashley ', 'United States ', 'US ');
INSERT INTO airports100 VALUES ('Aspen ', 'ASE', 'Aspen ', 'United States ', 'US ');
INSERT INTO airports100 VALUES ('Astoria ', 'AST', 'Astoria ', 'United States ', 'US ');
INSERT INTO airports100 VALUES ('Athens ', 'AHN', 'Athens ', 'United States ', 'US ');
INSERT INTO airports100 VALUES ('Athens ', 'ATO', 'Ohio University ', 'United States ', 'US ');
INSERT INTO airports100 VALUES ('Athens ', 'MMI', 'McMinn County ', 'United States ', 'US ');