-- Alex Zaharia
-- azaharia@calpoly.edu
-- May 2, 2023

INSERT INTO teachers VALUES ('MACROSTIE',  'MIN', 101);
INSERT INTO teachers VALUES ('COVIN',  'JEROME', 102);
INSERT INTO teachers VALUES ('MOYER',  'OTHA', 103);
INSERT INTO teachers VALUES ('NIBLER',  'JERLENE', 104);
INSERT INTO teachers VALUES ('MARROTTE',  'KIRK', 105);
INSERT INTO teachers VALUES ('TARRING',  'LEIA', 106);
INSERT INTO teachers VALUES ('URSERY',  'CHARMAINE', 107);
INSERT INTO teachers VALUES ('ONDERSMA',  'LORIA', 108);
INSERT INTO teachers VALUES ('KAWA',  'GORDON', 109);
INSERT INTO teachers VALUES ('SUMPTION',  'GEORGETTA', 110);
INSERT INTO teachers VALUES ('KRIENER',  'BILLIE', 111);
INSERT INTO teachers VALUES ('SUGAI',  'ALFREDA', 112);