-- Alex Zaharia
-- azaharia@calpoly.edu
-- May 2, 2023


INSERT INTO CarNames VALUES (1, 'chevrolet', 'chevrolet chevelle malibu');
INSERT INTO CarNames VALUES (2, 'buick', 'buick skylark 320');
INSERT INTO CarNames VALUES (3, 'plymouth', 'plymouth satellite');
INSERT INTO CarNames VALUES (4, 'amc', 'amc rebel sst');
INSERT INTO CarNames VALUES (5, 'ford', 'ford torino');
INSERT INTO CarNames VALUES (6, 'ford', 'ford galaxie 500');
INSERT INTO CarNames VALUES (7, 'chevrolet', 'chevrolet impala');
INSERT INTO CarNames VALUES (8, 'plymouth', 'plymouth fury iii');
INSERT INTO CarNames VALUES (9, 'pontiac', 'pontiac catalina');
INSERT INTO CarNames VALUES (10, 'amc', 'amc ambassador dpl');
INSERT INTO CarNames VALUES (11, 'citroen', 'citroen ds-21 pallas');
INSERT INTO CarNames VALUES (12, 'chevrolet', 'chevrolet chevelle concours (sw)');
INSERT INTO CarNames VALUES (13, 'ford', 'ford torino (sw)');
INSERT INTO CarNames VALUES (14, 'plymouth', 'plymouth satellite (sw)');
INSERT INTO CarNames VALUES (15, 'amc', 'amc rebel sst (sw)');
INSERT INTO CarNames VALUES (16, 'dodge', 'dodge challenger se');
INSERT INTO CarNames VALUES (17, 'plymouth', 'plymouth cuda 340');
INSERT INTO CarNames VALUES (18, 'ford', 'ford mustang boss 302');
INSERT INTO CarNames VALUES (19, 'chevrolet', 'chevrolet monte carlo');
INSERT INTO CarNames VALUES (20, 'buick', 'buick estate wagon (sw)');
INSERT INTO CarNames VALUES (21, 'toyota', 'toyota corona mark ii');
INSERT INTO CarNames VALUES (22, 'plymouth', 'plymouth duster');
INSERT INTO CarNames VALUES (23, 'amc', 'amc hornet');
INSERT INTO CarNames VALUES (24, 'ford', 'ford maverick');
INSERT INTO CarNames VALUES (25, 'datsun', 'datsun pl510');
INSERT INTO CarNames VALUES (26, 'volkswagen', 'volkswagen 1131 deluxe sedan');
INSERT INTO CarNames VALUES (27, 'peugeot', 'peugeot 504');
INSERT INTO CarNames VALUES (28, 'audi', 'audi 100 ls');
INSERT INTO CarNames VALUES (29, 'saab', 'saab 99e');
INSERT INTO CarNames VALUES (30, 'bmw', 'bmw 2002');
INSERT INTO CarNames VALUES (31, 'amc', 'amc gremlin');
INSERT INTO CarNames VALUES (32, 'ford', 'ford f250');
INSERT INTO CarNames VALUES (33, 'chevrolet', 'chevy c20');
INSERT INTO CarNames VALUES (34, 'dodge', 'dodge d200');
INSERT INTO CarNames VALUES (35, 'hi', 'hi 1200d');
INSERT INTO CarNames VALUES (36, 'datsun', 'datsun pl510');
INSERT INTO CarNames VALUES (37, 'chevrolet', 'chevrolet vega 2300');
INSERT INTO CarNames VALUES (38, 'toyota', 'toyota corona');
INSERT INTO CarNames VALUES (39, 'ford', 'ford pinto');
INSERT INTO CarNames VALUES (40, 'volkswagen', 'volkswagen super beetle 117');
INSERT INTO CarNames VALUES (41, 'amc', 'amc gremlin');
INSERT INTO CarNames VALUES (42, 'plymouth', 'plymouth satellite custom');
INSERT INTO CarNames VALUES (43, 'chevrolet', 'chevrolet chevelle malibu');
INSERT INTO CarNames VALUES (44, 'ford', 'ford torino 500');
INSERT INTO CarNames VALUES (45, 'amc', 'amc matador');
INSERT INTO CarNames VALUES (46, 'chevrolet', 'chevrolet impala');
INSERT INTO CarNames VALUES (47, 'pontiac', 'pontiac catalina brougham');
INSERT INTO CarNames VALUES (48, 'ford', 'ford galaxie 500');
INSERT INTO CarNames VALUES (49, 'plymouth', 'plymouth fury iii');
INSERT INTO CarNames VALUES (50, 'dodge', 'dodge monaco (sw)');
INSERT INTO CarNames VALUES (51, 'ford', 'ford country squire (sw)');
INSERT INTO CarNames VALUES (52, 'pontiac', 'pontiac safari (sw)');
INSERT INTO CarNames VALUES (53, 'amc', 'amc hornet sportabout (sw)');
INSERT INTO CarNames VALUES (54, 'chevrolet', 'chevrolet vega (sw)');
INSERT INTO CarNames VALUES (55, 'pontiac', 'pontiac firebird');
INSERT INTO CarNames VALUES (56, 'ford', 'ford mustang');
INSERT INTO CarNames VALUES (57, 'mercury', 'mercury capri 2000');
INSERT INTO CarNames VALUES (58, 'opel', 'opel 1900');
INSERT INTO CarNames VALUES (59, 'peugeot', 'peugeot 304');
INSERT INTO CarNames VALUES (60, 'fiat', 'fiat 124b');
INSERT INTO CarNames VALUES (61, 'toyota', 'toyota corolla 1200');
INSERT INTO CarNames VALUES (62, 'datsun', 'datsun 1200');
INSERT INTO CarNames VALUES (63, 'volkswagen', 'volkswagen model 111');
INSERT INTO CarNames VALUES (64, 'plymouth', 'plymouth cricket');
INSERT INTO CarNames VALUES (65, 'toyota', 'toyota corona hardtop');
INSERT INTO CarNames VALUES (66, 'dodge', 'dodge colt hardtop');
INSERT INTO CarNames VALUES (67, 'volkswagen', 'volkswagen type 3');
INSERT INTO CarNames VALUES (68, 'chevrolet', 'chevrolet vega');
INSERT INTO CarNames VALUES (69, 'ford', 'ford pinto runabout');
INSERT INTO CarNames VALUES (70, 'chevrolet', 'chevrolet impala');
INSERT INTO CarNames VALUES (71, 'pontiac', 'pontiac catalina');
INSERT INTO CarNames VALUES (72, 'plymouth', 'plymouth fury iii');
INSERT INTO CarNames VALUES (73, 'ford', 'ford galaxie 500');
INSERT INTO CarNames VALUES (74, 'amc', 'amc ambassador sst');
INSERT INTO CarNames VALUES (75, 'mercury', 'mercury marquis');
INSERT INTO CarNames VALUES (76, 'buick', 'buick lesabre custom');
INSERT INTO CarNames VALUES (77, 'oldsmobile', 'oldsmobile delta 88 royale');
INSERT INTO CarNames VALUES (78, 'chrysler', 'chrysler newport royal');
INSERT INTO CarNames VALUES (79, 'mazda', 'mazda rx2 coupe');
INSERT INTO CarNames VALUES (80, 'amc', 'amc matador (sw)');
INSERT INTO CarNames VALUES (81, 'chevrolet', 'chevrolet chevelle concours (sw)');
INSERT INTO CarNames VALUES (82, 'ford', 'ford gran torino (sw)');
INSERT INTO CarNames VALUES (83, 'plymouth', 'plymouth satellite custom (sw)');
INSERT INTO CarNames VALUES (84, 'volvo', 'volvo 145e (sw)');
INSERT INTO CarNames VALUES (85, 'volkswagen', 'volkswagen 411 (sw)');
INSERT INTO CarNames VALUES (86, 'peugeot', 'peugeot 504 (sw)');
INSERT INTO CarNames VALUES (87, 'renault', 'renault 12 (sw)');
INSERT INTO CarNames VALUES (88, 'ford', 'ford pinto (sw)');
INSERT INTO CarNames VALUES (89, 'datsun', 'datsun 510 (sw)');
INSERT INTO CarNames VALUES (90, 'toyota', 'toyota corona mark ii (sw)');
INSERT INTO CarNames VALUES (91, 'dodge', 'dodge colt (sw)');
INSERT INTO CarNames VALUES (92, 'toyota', 'toyota corolla 1600 (sw)');
INSERT INTO CarNames VALUES (93, 'buick', 'buick century 350');
INSERT INTO CarNames VALUES (94, 'amc', 'amc matador');
INSERT INTO CarNames VALUES (95, 'chevrolet', 'chevrolet malibu');
INSERT INTO CarNames VALUES (96, 'ford', 'ford gran torino');
INSERT INTO CarNames VALUES (97, 'dodge', 'dodge coronet custom');
INSERT INTO CarNames VALUES (98, 'mercury', 'mercury marquis brougham');
INSERT INTO CarNames VALUES (99, 'chevrolet', 'chevrolet caprice classic');
INSERT INTO CarNames VALUES (100, 'ford', 'ford ltd');
INSERT INTO CarNames VALUES (101, 'plymouth', 'plymouth fury gran sedan');
INSERT INTO CarNames VALUES (102, 'chrysler', 'chrysler new yorker brougham');
INSERT INTO CarNames VALUES (103, 'buick', 'buick electra 225 custom');
INSERT INTO CarNames VALUES (104, 'amc', 'amc ambassador brougham');
INSERT INTO CarNames VALUES (105, 'plymouth', 'plymouth valiant');
INSERT INTO CarNames VALUES (106, 'chevrolet', 'chevrolet nova custom');
INSERT INTO CarNames VALUES (107, 'amc', 'amc hornet');
INSERT INTO CarNames VALUES (108, 'ford', 'ford maverick');
INSERT INTO CarNames VALUES (109, 'plymouth', 'plymouth duster');
INSERT INTO CarNames VALUES (110, 'volkswagen', 'volkswagen super beetle');
INSERT INTO CarNames VALUES (111, 'chevrolet', 'chevrolet impala');
INSERT INTO CarNames VALUES (112, 'ford', 'ford country');
INSERT INTO CarNames VALUES (113, 'plymouth', 'plymouth custom suburb');
INSERT INTO CarNames VALUES (114, 'oldsmobile', 'oldsmobile vista cruiser');
INSERT INTO CarNames VALUES (115, 'amc', 'amc gremlin');
INSERT INTO CarNames VALUES (116, 'toyota', 'toyota carina');
INSERT INTO CarNames VALUES (117, 'chevrolet', 'chevrolet vega');
INSERT INTO CarNames VALUES (118, 'datsun', 'datsun 610');
INSERT INTO CarNames VALUES (119, 'mazda', 'mazda rx3');
INSERT INTO CarNames VALUES (120, 'ford', 'ford pinto');
INSERT INTO CarNames VALUES (121, 'mercury', 'mercury capri v6');
INSERT INTO CarNames VALUES (122, 'fiat', 'fiat 124 sport coupe');
INSERT INTO CarNames VALUES (123, 'chevrolet', 'chevrolet monte carlo s');
INSERT INTO CarNames VALUES (124, 'pontiac', 'pontiac grand prix');
INSERT INTO CarNames VALUES (125, 'fiat', 'fiat 128');
INSERT INTO CarNames VALUES (126, 'opel', 'opel manta');
INSERT INTO CarNames VALUES (127, 'audi', 'audi 100ls');
INSERT INTO CarNames VALUES (128, 'volvo', 'volvo 144ea');
INSERT INTO CarNames VALUES (129, 'dodge', 'dodge dart custom');
INSERT INTO CarNames VALUES (130, 'saab', 'saab 99le');
INSERT INTO CarNames VALUES (131, 'toyota', 'toyota mark ii');
INSERT INTO CarNames VALUES (132, 'oldsmobile', 'oldsmobile omega');
INSERT INTO CarNames VALUES (133, 'plymouth', 'plymouth duster');
INSERT INTO CarNames VALUES (134, 'ford', 'ford maverick');
INSERT INTO CarNames VALUES (135, 'amc', 'amc hornet');
INSERT INTO CarNames VALUES (136, 'chevrolet', 'chevrolet nova');
INSERT INTO CarNames VALUES (137, 'datsun', 'datsun b210');
INSERT INTO CarNames VALUES (138, 'ford', 'ford pinto');
INSERT INTO CarNames VALUES (139, 'toyota', 'toyota corolla 1200');
INSERT INTO CarNames VALUES (140, 'chevrolet', 'chevrolet vega');
INSERT INTO CarNames VALUES (141, 'chevrolet', 'chevrolet chevelle malibu classic');
INSERT INTO CarNames VALUES (142, 'amc', 'amc matador');
INSERT INTO CarNames VALUES (143, 'plymouth', 'plymouth satellite sebring');
INSERT INTO CarNames VALUES (144, 'ford', 'ford gran torino');
INSERT INTO CarNames VALUES (145, 'buick', 'buick century luxus (sw)');
INSERT INTO CarNames VALUES (146, 'dodge', 'dodge coronet custom (sw)');
INSERT INTO CarNames VALUES (147, 'ford', 'ford gran torino (sw)');
INSERT INTO CarNames VALUES (148, 'amc', 'amc matador (sw)');
INSERT INTO CarNames VALUES (149, 'audi', 'audi fox');
INSERT INTO CarNames VALUES (150, 'volkswagen', 'volkswagen dasher');
INSERT INTO CarNames VALUES (151, 'opel', 'opel manta');
INSERT INTO CarNames VALUES (152, 'toyota', 'toyota corona');
INSERT INTO CarNames VALUES (153, 'datsun', 'datsun 710');
INSERT INTO CarNames VALUES (154, 'dodge', 'dodge colt');
INSERT INTO CarNames VALUES (155, 'fiat', 'fiat 128');
INSERT INTO CarNames VALUES (156, 'fiat', 'fiat 124 tc');
INSERT INTO CarNames VALUES (157, 'honda', 'honda civic');
INSERT INTO CarNames VALUES (158, 'subaru', 'subaru');
INSERT INTO CarNames VALUES (159, 'fiat', 'fiat x1.9');
INSERT INTO CarNames VALUES (160, 'plymouth', 'plymouth valiant custom');
INSERT INTO CarNames VALUES (161, 'chevrolet', 'chevrolet nova');
INSERT INTO CarNames VALUES (162, 'mercury', 'mercury monarch');
INSERT INTO CarNames VALUES (163, 'ford', 'ford maverick');
INSERT INTO CarNames VALUES (164, 'pontiac', 'pontiac catalina');
INSERT INTO CarNames VALUES (165, 'chevrolet', 'chevrolet bel air');
INSERT INTO CarNames VALUES (166, 'plymouth', 'plymouth grand fury');
INSERT INTO CarNames VALUES (167, 'ford', 'ford ltd');
INSERT INTO CarNames VALUES (168, 'buick', 'buick century');
INSERT INTO CarNames VALUES (169, 'chevrolet', 'chevrolet chevelle malibu');
INSERT INTO CarNames VALUES (170, 'amc', 'amc matador');
INSERT INTO CarNames VALUES (171, 'plymouth', 'plymouth fury');
INSERT INTO CarNames VALUES (172, 'buick', 'buick skyhawk');
INSERT INTO CarNames VALUES (173, 'chevrolet', 'chevrolet monza 2+2');
INSERT INTO CarNames VALUES (174, 'ford', 'ford mustang ii');
INSERT INTO CarNames VALUES (175, 'toyota', 'toyota corolla');
INSERT INTO CarNames VALUES (176, 'ford', 'ford pinto');
INSERT INTO CarNames VALUES (177, 'amc', 'amc gremlin');
INSERT INTO CarNames VALUES (178, 'pontiac', 'pontiac astro');
INSERT INTO CarNames VALUES (179, 'toyota', 'toyota corona');
INSERT INTO CarNames VALUES (180, 'volkswagen', 'volkswagen dasher');
INSERT INTO CarNames VALUES (181, 'datsun', 'datsun 710');
INSERT INTO CarNames VALUES (182, 'ford', 'ford pinto');
INSERT INTO CarNames VALUES (183, 'volkswagen', 'volkswagen rabbit');
INSERT INTO CarNames VALUES (184, 'amc', 'amc pacer');
INSERT INTO CarNames VALUES (185, 'audi', 'audi 100ls');
INSERT INTO CarNames VALUES (186, 'peugeot', 'peugeot 504');
INSERT INTO CarNames VALUES (187, 'volvo', 'volvo 244dl');
INSERT INTO CarNames VALUES (188, 'saab', 'saab 99le');
INSERT INTO CarNames VALUES (189, 'honda', 'honda civic cvcc');
INSERT INTO CarNames VALUES (190, 'fiat', 'fiat 131');
INSERT INTO CarNames VALUES (191, 'opel', 'opel 1900');
INSERT INTO CarNames VALUES (192, 'capri', 'capri ii');
INSERT INTO CarNames VALUES (193, 'dodge', 'dodge colt');
INSERT INTO CarNames VALUES (194, 'renault', 'renault 12tl');
INSERT INTO CarNames VALUES (195, 'chevrolet', 'chevrolet chevelle malibu classic');
INSERT INTO CarNames VALUES (196, 'dodge', 'dodge coronet brougham');
INSERT INTO CarNames VALUES (197, 'amc', 'amc matador');
INSERT INTO CarNames VALUES (198, 'ford', 'ford gran torino');
INSERT INTO CarNames VALUES (199, 'plymouth', 'plymouth valiant');
INSERT INTO CarNames VALUES (200, 'chevrolet', 'chevrolet nova');
INSERT INTO CarNames VALUES (201, 'ford', 'ford maverick');
INSERT INTO CarNames VALUES (202, 'amc', 'amc hornet');
INSERT INTO CarNames VALUES (203, 'chevrolet', 'chevrolet chevette');
INSERT INTO CarNames VALUES (204, 'chevrolet', 'chevrolet woody');
INSERT INTO CarNames VALUES (205, 'volkswagen', 'vw rabbit');
INSERT INTO CarNames VALUES (206, 'honda', 'honda civic');
INSERT INTO CarNames VALUES (207, 'dodge', 'dodge aspen se');
INSERT INTO CarNames VALUES (208, 'ford', 'ford granada ghia');
INSERT INTO CarNames VALUES (209, 'pontiac', 'pontiac ventura sj');
INSERT INTO CarNames VALUES (210, 'amc', 'amc pacer d/l');
INSERT INTO CarNames VALUES (211, 'volkswagen', 'volkswagen rabbit');
INSERT INTO CarNames VALUES (212, 'datsun', 'datsun b-210');
INSERT INTO CarNames VALUES (213, 'toyota', 'toyota corolla');
INSERT INTO CarNames VALUES (214, 'ford', 'ford pinto');
INSERT INTO CarNames VALUES (215, 'volvo', 'volvo 245');
INSERT INTO CarNames VALUES (216, 'plymouth', 'plymouth volare premier v8');
INSERT INTO CarNames VALUES (217, 'peugeot', 'peugeot 504');
INSERT INTO CarNames VALUES (218, 'toyota', 'toyota mark ii');
INSERT INTO CarNames VALUES (219, 'mercedes-benz', 'mercedes-benz 280s');
INSERT INTO CarNames VALUES (220, 'cadillac', 'cadillac seville');
INSERT INTO CarNames VALUES (221, 'chevrolet', 'chevy c10');
INSERT INTO CarNames VALUES (222, 'ford', 'ford f108');
INSERT INTO CarNames VALUES (223, 'dodge', 'dodge d100');
INSERT INTO CarNames VALUES (224, 'honda', 'honda accord cvcc');
INSERT INTO CarNames VALUES (225, 'buick', 'buick opel isuzu deluxe');
INSERT INTO CarNames VALUES (226, 'renault', 'renault 5 gtl');
INSERT INTO CarNames VALUES (227, 'plymouth', 'plymouth arrow gs');
INSERT INTO CarNames VALUES (228, 'datsun', 'datsun f-10 hatchback');
INSERT INTO CarNames VALUES (229, 'chevrolet', 'chevrolet caprice classic');
INSERT INTO CarNames VALUES (230, 'oldsmobile', 'oldsmobile cutlass supreme');
INSERT INTO CarNames VALUES (231, 'dodge', 'dodge monaco brougham');
INSERT INTO CarNames VALUES (232, 'mercury', 'mercury cougar brougham');
INSERT INTO CarNames VALUES (233, 'chevrolet', 'chevrolet concours');
INSERT INTO CarNames VALUES (234, 'buick', 'buick skylark');
INSERT INTO CarNames VALUES (235, 'plymouth', 'plymouth volare custom');
INSERT INTO CarNames VALUES (236, 'ford', 'ford granada');
INSERT INTO CarNames VALUES (237, 'pontiac', 'pontiac grand prix lj');
INSERT INTO CarNames VALUES (238, 'chevrolet', 'chevrolet monte carlo landau');
INSERT INTO CarNames VALUES (239, 'chrysler', 'chrysler cordoba');
INSERT INTO CarNames VALUES (240, 'ford', 'ford thunderbird');
INSERT INTO CarNames VALUES (241, 'volkswagen', 'volkswagen rabbit custom');
INSERT INTO CarNames VALUES (242, 'pontiac', 'pontiac sunbird coupe');
INSERT INTO CarNames VALUES (243, 'toyota', 'toyota corolla liftback');
INSERT INTO CarNames VALUES (244, 'ford', 'ford mustang ii 2+2');
INSERT INTO CarNames VALUES (245, 'chevrolet', 'chevrolet chevette');
INSERT INTO CarNames VALUES (246, 'dodge', 'dodge colt m/m');
INSERT INTO CarNames VALUES (247, 'subaru', 'subaru dl');
INSERT INTO CarNames VALUES (248, 'volkswagen', 'volkswagen dasher');
INSERT INTO CarNames VALUES (249, 'datsun', 'datsun 810');
INSERT INTO CarNames VALUES (250, 'bmw', 'bmw 320i');
INSERT INTO CarNames VALUES (251, 'mazda', 'mazda rx-4');
INSERT INTO CarNames VALUES (252, 'volkswagen', 'volkswagen rabbit custom diesel');
INSERT INTO CarNames VALUES (253, 'ford', 'ford fiesta');
INSERT INTO CarNames VALUES (254, 'mazda', 'mazda glc deluxe');
INSERT INTO CarNames VALUES (255, 'datsun', 'datsun b210 gx');
INSERT INTO CarNames VALUES (256, 'honda', 'honda civic cvcc');
INSERT INTO CarNames VALUES (257, 'oldsmobile', 'oldsmobile cutlass salon brougham');
INSERT INTO CarNames VALUES (258, 'dodge', 'dodge diplomat');
INSERT INTO CarNames VALUES (259, 'mercury', 'mercury monarch ghia');
INSERT INTO CarNames VALUES (260, 'pontiac', 'pontiac phoenix lj');
INSERT INTO CarNames VALUES (261, 'chevrolet', 'chevrolet malibu');
INSERT INTO CarNames VALUES (262, 'ford', 'ford fairmont (auto)');
INSERT INTO CarNames VALUES (263, 'ford', 'ford fairmont (man)');
INSERT INTO CarNames VALUES (264, 'plymouth', 'plymouth volare');
INSERT INTO CarNames VALUES (265, 'amc', 'amc concord');
INSERT INTO CarNames VALUES (266, 'buick', 'buick century special');
INSERT INTO CarNames VALUES (267, 'mercury', 'mercury zephyr');
INSERT INTO CarNames VALUES (268, 'dodge', 'dodge aspen');
INSERT INTO CarNames VALUES (269, 'amc', 'amc concord d/l');
INSERT INTO CarNames VALUES (270, 'chevrolet', 'chevrolet monte carlo landau');
INSERT INTO CarNames VALUES (271, 'buick', 'buick regal sport coupe (turbo)');
INSERT INTO CarNames VALUES (272, 'ford', 'ford futura');
INSERT INTO CarNames VALUES (273, 'dodge', 'dodge magnum xe');
INSERT INTO CarNames VALUES (274, 'chevrolet', 'chevrolet chevette');
INSERT INTO CarNames VALUES (275, 'toyota', 'toyota corona');
INSERT INTO CarNames VALUES (276, 'datsun', 'datsun 510');
INSERT INTO CarNames VALUES (277, 'dodge', 'dodge omni');
INSERT INTO CarNames VALUES (278, 'toyota', 'toyota celica gt liftback');
INSERT INTO CarNames VALUES (279, 'plymouth', 'plymouth sapporo');
INSERT INTO CarNames VALUES (280, 'oldsmobile', 'oldsmobile starfire sx');
INSERT INTO CarNames VALUES (281, 'datsun', 'datsun 200-sx');
INSERT INTO CarNames VALUES (282, 'audi', 'audi 5000');
INSERT INTO CarNames VALUES (283, 'volvo', 'volvo 264gl');
INSERT INTO CarNames VALUES (284, 'saab', 'saab 99gle');
INSERT INTO CarNames VALUES (285, 'peugeot', 'peugeot 604sl');
INSERT INTO CarNames VALUES (286, 'volkswagen', 'volkswagen scirocco');
INSERT INTO CarNames VALUES (287, 'honda', 'honda accord lx');
INSERT INTO CarNames VALUES (288, 'pontiac', 'pontiac lemans v6');
INSERT INTO CarNames VALUES (289, 'mercury', 'mercury zephyr 6');
INSERT INTO CarNames VALUES (290, 'ford', 'ford fairmont 4');
INSERT INTO CarNames VALUES (291, 'amc', 'amc concord dl 6');
INSERT INTO CarNames VALUES (292, 'dodge', 'dodge aspen 6');
INSERT INTO CarNames VALUES (293, 'chevrolet', 'chevrolet caprice classic');
INSERT INTO CarNames VALUES (294, 'ford', 'ford ltd landau');
INSERT INTO CarNames VALUES (295, 'mercury', 'mercury grand marquis');
INSERT INTO CarNames VALUES (296, 'dodge', 'dodge st. regis');
INSERT INTO CarNames VALUES (297, 'buick', 'buick estate wagon (sw)');
INSERT INTO CarNames VALUES (298, 'ford', 'ford country squire (sw)');
INSERT INTO CarNames VALUES (299, 'chevrolet', 'chevrolet malibu classic (sw)');
INSERT INTO CarNames VALUES (300, 'chrysler', 'chrysler lebaron town @ country (sw)');
INSERT INTO CarNames VALUES (301, 'volkswagen', 'vw rabbit custom');
INSERT INTO CarNames VALUES (302, 'mazda',  'mazda glc deluxe');
INSERT INTO CarNames VALUES (303, 'dodge', 'dodge colt hatchback custom');
INSERT INTO CarNames VALUES (304, 'amc', 'amc spirit dl');
INSERT INTO CarNames VALUES (305, 'mercedes', 'mercedes benz 300d');
INSERT INTO CarNames VALUES (306, 'cadillac', 'cadillac eldorado');
INSERT INTO CarNames VALUES (307, 'peugeot', 'peugeot 504');
INSERT INTO CarNames VALUES (308, 'oldsmobile', 'oldsmobile cutlass salon brougham');
INSERT INTO CarNames VALUES (309, 'plymouth', 'plymouth horizon');
INSERT INTO CarNames VALUES (310, 'plymouth', 'plymouth horizon tc3');
INSERT INTO CarNames VALUES (311, 'datsun', 'datsun 210');
INSERT INTO CarNames VALUES (312, 'fiat', 'fiat strada custom');
INSERT INTO CarNames VALUES (313, 'buick', 'buick skylark limited');
INSERT INTO CarNames VALUES (314, 'chevrolet', 'chevrolet citation');
INSERT INTO CarNames VALUES (315, 'oldsmobile', 'oldsmobile omega brougham');
INSERT INTO CarNames VALUES (316, 'pontiac', 'pontiac phoenix');
INSERT INTO CarNames VALUES (317, 'volkswagen', 'vw rabbit');
INSERT INTO CarNames VALUES (318, 'toyota', 'toyota corolla tercel');
INSERT INTO CarNames VALUES (319, 'chevrolet', 'chevrolet chevette');
INSERT INTO CarNames VALUES (320, 'datsun', 'datsun 310');
INSERT INTO CarNames VALUES (321, 'chevrolet', 'chevrolet citation');
INSERT INTO CarNames VALUES (322, 'ford', 'ford fairmont');
INSERT INTO CarNames VALUES (323, 'amc', 'amc concord');
INSERT INTO CarNames VALUES (324, 'dodge', 'dodge aspen');
INSERT INTO CarNames VALUES (325, 'audi', 'audi 4000');
INSERT INTO CarNames VALUES (326, 'toyota', 'toyota corona liftback');
INSERT INTO CarNames VALUES (327, 'mazda', 'mazda 626');
INSERT INTO CarNames VALUES (328, 'datsun', 'datsun 510 hatchback');
INSERT INTO CarNames VALUES (329, 'toyota', 'toyota corolla');
INSERT INTO CarNames VALUES (330, 'mazda', 'mazda glc');
INSERT INTO CarNames VALUES (331, 'dodge', 'dodge colt');
INSERT INTO CarNames VALUES (332, 'datsun', 'datsun 210');
INSERT INTO CarNames VALUES (333, 'volkswagen', 'vw rabbit c (diesel)');
INSERT INTO CarNames VALUES (334, 'volkswagen', 'vw dasher (diesel)');
INSERT INTO CarNames VALUES (335, 'audi', 'audi 5000s (diesel)');
INSERT INTO CarNames VALUES (336, 'mercedes-benz', 'mercedes-benz 240d');
INSERT INTO CarNames VALUES (337, 'honda', 'honda civic 1500 gl');
INSERT INTO CarNames VALUES (338, 'renault', 'renault lecar deluxe');
INSERT INTO CarNames VALUES (339, 'subaru', 'subaru dl');
INSERT INTO CarNames VALUES (340,  'volkswagen', 'volkswagen rabbit');
INSERT INTO CarNames VALUES (341, 'datsun', 'datsun 280-zx');
INSERT INTO CarNames VALUES (342, 'mazda', 'mazda rx-7 gs');
INSERT INTO CarNames VALUES (343, 'triumph', 'triumph tr7 coupe');
INSERT INTO CarNames VALUES (344, 'ford', 'ford mustang cobra');
INSERT INTO CarNames VALUES (345, 'honda', 'honda accord');
INSERT INTO CarNames VALUES (346, 'plymouth', 'plymouth reliant');
INSERT INTO CarNames VALUES (347, 'buick', 'buick skylark');
INSERT INTO CarNames VALUES (348, 'dodge', 'dodge aries wagon (sw)');
INSERT INTO CarNames VALUES (349, 'chevrolet', 'chevrolet citation');
INSERT INTO CarNames VALUES (350, 'plymouth', 'plymouth reliant');
INSERT INTO CarNames VALUES (351, 'toyota', 'toyota starlet');
INSERT INTO CarNames VALUES (352, 'plymouth', 'plymouth champ');
INSERT INTO CarNames VALUES (353, 'honda', 'honda civic 1300');
INSERT INTO CarNames VALUES (354, 'subaru', 'subaru');
INSERT INTO CarNames VALUES (355, 'datsun', 'datsun 210 mpg');
INSERT INTO CarNames VALUES (356, 'toyota', 'toyota tercel');
INSERT INTO CarNames VALUES (357, 'mazda', 'mazda glc 4');
INSERT INTO CarNames VALUES (358, 'plymouth', 'plymouth horizon 4');
INSERT INTO CarNames VALUES (359, 'ford', 'ford escort 4w');
INSERT INTO CarNames VALUES (360, 'ford', 'ford escort 2h');
INSERT INTO CarNames VALUES (361, 'volkswagen', 'volkswagen jetta');
INSERT INTO CarNames VALUES (362, 'renault', 'renault 18i');
INSERT INTO CarNames VALUES (363, 'honda', 'honda prelude');
INSERT INTO CarNames VALUES (364, 'toyota', 'toyota corolla');
INSERT INTO CarNames VALUES (365, 'datsun', 'datsun 200sx');
INSERT INTO CarNames VALUES (366, 'mazda', 'mazda 626');
INSERT INTO CarNames VALUES (367, 'peugeot', 'peugeot 505s turbo diesel');
INSERT INTO CarNames VALUES (368, 'saab', 'saab 900s');
INSERT INTO CarNames VALUES (369, 'volvo', 'volvo diesel');
INSERT INTO CarNames VALUES (370, 'toyota', 'toyota cressida');
INSERT INTO CarNames VALUES (371, 'datsun', 'datsun 810 maxima');
INSERT INTO CarNames VALUES (372, 'buick', 'buick century');
INSERT INTO CarNames VALUES (373, 'oldsmobile', 'oldsmobile cutlass ls');
INSERT INTO CarNames VALUES (374, 'ford', 'ford granada gl');
INSERT INTO CarNames VALUES (375, 'chrysler', 'chrysler lebaron salon');
INSERT INTO CarNames VALUES (376, 'chevrolet', 'chevrolet cavalier');
INSERT INTO CarNames VALUES (377, 'chevrolet', 'chevrolet cavalier wagon');
INSERT INTO CarNames VALUES (378, 'chevrolet', 'chevrolet cavalier 2-door');
INSERT INTO CarNames VALUES (379, 'pontiac', 'pontiac j2000 se hatchback');
INSERT INTO CarNames VALUES (380, 'dodge', 'dodge aries se');
INSERT INTO CarNames VALUES (381, 'pontiac', 'pontiac phoenix');
INSERT INTO CarNames VALUES (382, 'ford', 'ford fairmont futura');
INSERT INTO CarNames VALUES (383, 'amc', 'amc concord dl');
INSERT INTO CarNames VALUES (384, 'volkswagen', 'volkswagen rabbit l');
INSERT INTO CarNames VALUES (385, 'mazda', 'mazda glc custom l');
INSERT INTO CarNames VALUES (386, 'mazda', 'mazda glc custom');
INSERT INTO CarNames VALUES (387, 'plymouth', 'plymouth horizon miser');
INSERT INTO CarNames VALUES (388, 'mercury', 'mercury lynx l');
INSERT INTO CarNames VALUES (389, 'nissan', 'nissan stanza xe');
INSERT INTO CarNames VALUES (390, 'honda', 'honda accord');
INSERT INTO CarNames VALUES (391, 'toyota', 'toyota corolla');
INSERT INTO CarNames VALUES (392, 'honda', 'honda civic');
INSERT INTO CarNames VALUES (393, 'honda', 'honda civic (auto)');
INSERT INTO CarNames VALUES (394, 'datsun', 'datsun 310 gx');
INSERT INTO CarNames VALUES (395, 'buick', 'buick century limited');
INSERT INTO CarNames VALUES (396, 'oldsmobile', 'oldsmobile cutlass ciera (diesel)');
INSERT INTO CarNames VALUES (397, 'chrysler', 'chrysler lebaron medallion');
INSERT INTO CarNames VALUES (398, 'ford', 'ford granada l');
INSERT INTO CarNames VALUES (399, 'toyota', 'toyota celica gt');
INSERT INTO CarNames VALUES (400, 'dodge', 'dodge charger 2.2');
INSERT INTO CarNames VALUES (401, 'chevrolet', 'chevrolet camaro');
INSERT INTO CarNames VALUES (402, 'ford', 'ford mustang gl');
INSERT INTO CarNames VALUES (403, 'volkswagen', 'vw pickup');
INSERT INTO CarNames VALUES (404, 'dodge', 'dodge rampage');
INSERT INTO CarNames VALUES (405, 'ford', 'ford ranger');
INSERT INTO CarNames VALUES (406, 'chevrolet', 'chevy s-10');