-- Alex Zaharia
-- azaharia@calpoly.edu
-- May 2, 2023

INSERT INTO appellations VALUES (1, 'Alexander Valley', 'Sonoma', 'California', 'North Coast', 'Yes');
INSERT INTO appellations VALUES (2, 'Amador County', 'Amador', 'California', 'Sierra Foothills', 'No');
INSERT INTO appellations VALUES (3, 'Amador-Mendocino-Sonoma Counties', 'N/A', 'California', 'N/A', 'No');
INSERT INTO appellations VALUES (4, 'Anderson Valley', 'Mendocino', 'California', 'North Coast', 'Yes');
INSERT INTO appellations VALUES (5, 'Arroyo Grande Valley', 'San Luis Obispo', 'California', 'Central Coast', 'Yes');
INSERT INTO appellations VALUES (6, 'Atlas Peak', 'Napa', 'California', 'North Coast', 'Yes');
INSERT INTO appellations VALUES (7, 'Bennett Valley', 'Sonoma', 'California', 'North Coast', 'Yes');
INSERT INTO appellations VALUES (8, 'Calaveras County', 'Calaveras', 'California', 'Sierra Foothills', 'No');
INSERT INTO appellations VALUES (9, 'California', 'N/A', 'California', 'California', 'No');
INSERT INTO appellations VALUES (10, 'Carneros', 'Napa', 'California', 'North Coast', 'Yes');
INSERT INTO appellations VALUES (11, 'Central Coast', 'N/A', 'California', 'Central Coast', 'Yes');
INSERT INTO appellations VALUES (12, 'Chalk Hill', 'Sonoma', 'California', 'North Coast', 'Yes');
INSERT INTO appellations VALUES (13, 'Chalone', 'Monterey', 'California', 'Central Coast', 'Yes');
INSERT INTO appellations VALUES (14, 'Contra Costa County', 'Contra Costa', 'California', 'Santa Cruz Mountains', 'No');
INSERT INTO appellations VALUES (15, 'Dry Creek Valley', 'Sonoma', 'California', 'North Coast', 'Yes');
INSERT INTO appellations VALUES (16, 'Edna Valley', 'San Luis Obispo', 'California', 'Central Coast', 'Yes');
INSERT INTO appellations VALUES (17, 'Fiddletown', 'Amador', 'California', 'Sierra Foothills', 'Yes');
INSERT INTO appellations VALUES (18, 'Green Valley of Russian River Valley', 'Sonoma', 'California', 'North Coast', 'Yes');
INSERT INTO appellations VALUES (19, 'Guenoc Valley', 'Lake', 'California', 'North Coast', 'Yes');
INSERT INTO appellations VALUES (20, 'Happy Canyon of Santa Barbara', 'Santa Barbara', 'California', 'Central Coast', 'Yes');
INSERT INTO appellations VALUES (21, 'Howell Mountain', 'Napa', 'California', 'North Coast', 'Yes');
INSERT INTO appellations VALUES (22, 'Knights Valley', 'Sonoma', 'California', 'North Coast', 'Yes');
INSERT INTO appellations VALUES (23, 'Lake County', 'Lake', 'California', 'North Coast', 'No');
INSERT INTO appellations VALUES (24, 'Livermore Valley', 'Alameda', 'California', 'Santa Cruz Mountains', 'Yes');
INSERT INTO appellations VALUES (25, 'Lodi', 'San Joaquin', 'California', 'Central Valley', 'Yes');
INSERT INTO appellations VALUES (26, 'Mendocino County', 'Mendocino', 'California', 'North Coast', 'No');
INSERT INTO appellations VALUES (27, 'Monterey County', 'Monterey', 'California', 'Central Coast', 'No');
INSERT INTO appellations VALUES (28, 'Mount Harlan', 'San Benito', 'California', 'Central Coast', 'Yes');
INSERT INTO appellations VALUES (29, 'Mount Vedeer', 'Napa', 'California', 'North Coast', 'Yes');
INSERT INTO appellations VALUES (30, 'Napa Valley', 'Napa', 'California', 'North Coast', 'Yes');
INSERT INTO appellations VALUES (31, 'Napa-Sonoma counties', 'N/A', 'California', 'North Coast', 'No');
INSERT INTO appellations VALUES (32, 'North Coast', 'N/A', 'California', 'North Coast', 'Yes');
INSERT INTO appellations VALUES (33, 'Oakville', 'Napa', 'California', 'North Coast', 'Yes');
INSERT INTO appellations VALUES (34, 'Paso Robles', 'San Luis Obispo', 'California', 'Central Coast', 'Yes');
INSERT INTO appellations VALUES (35, 'Red Hills Lake County', 'Lake', 'California', 'North Coast', 'Yes');
INSERT INTO appellations VALUES (36, 'Rockpile', 'Sonoma', 'California', 'North Coast', 'Yes');
INSERT INTO appellations VALUES (37, 'Russian River Valley', 'Sonoma', 'California', 'North Coast', 'Yes');
INSERT INTO appellations VALUES (38, 'Rutherford', 'Napa', 'California', 'North Coast', 'Yes');
INSERT INTO appellations VALUES (39, 'San Luis Obispo County', 'San Luis Obispo', 'California', 'Central Coast', 'No');
INSERT INTO appellations VALUES (40, 'Santa Barbara County', 'Santa Barbara', 'California', 'Central Coast', 'No');
INSERT INTO appellations VALUES (41, 'Santa Cruz Mountains', 'N/A', 'California', 'Santa Cruz Mountains', 'Yes');
INSERT INTO appellations VALUES (42, 'Santa Lucia Highlands', 'Monterey', 'California', 'Central Coast', 'Yes');
INSERT INTO appellations VALUES (43, 'Santa Maria Valley', 'Santa Barbara', 'California', 'Central Coast', 'Yes');
INSERT INTO appellations VALUES (44, 'Santa Ynez Valley', 'Santa Barbara', 'California', 'Central Coast', 'Yes');
INSERT INTO appellations VALUES (45, 'Shenandoah Valley', 'Amador', 'California', 'Sierra Foothills', 'Yes');
INSERT INTO appellations VALUES (46, 'Sierra Foothills', 'N/A', 'California', 'Sierra Foothills', 'Yes');
INSERT INTO appellations VALUES (47, 'Solano County', 'Solano', 'California', 'North Coast', 'No');
INSERT INTO appellations VALUES (48, 'Sonoma Coast', 'Sonoma', 'California', 'North Coast', 'Yes');
INSERT INTO appellations VALUES (49, 'Sonoma County', 'Sonoma', 'California', 'North Coast', 'No');
INSERT INTO appellations VALUES (50, 'Sonoma Valley', 'Sonoma', 'California', 'North Coast', 'Yes');
INSERT INTO appellations VALUES (51, 'Sonoma-Lake Counties', 'N/A', 'California', 'North Coast', 'Yes');
INSERT INTO appellations VALUES (52, 'Spring Mountain District', 'Napa', 'California', 'North Coast', 'Yes');
INSERT INTO appellations VALUES (53, 'St. Helena', 'Napa', 'California', 'North Coast', 'Yes');
INSERT INTO appellations VALUES (54, 'Sta. Rita Hills', 'Santa Barbara', 'California', 'Central Coast', 'Yes');
INSERT INTO appellations VALUES (55, 'Stags Leap District', 'Napa', 'California', 'North Coast', 'Yes');
INSERT INTO appellations VALUES (56, 'Yolo County', 'Yolo', 'California', 'Central Valley', 'No');
INSERT INTO appellations VALUES (57, 'Yountville', 'Napa', 'California', 'North Coast', 'Yes');